name: 🚀 Deploy Laravel ke Shared Hosting

on:
  push:
    branches:
      - main  # branch utama untuk trigger deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install dependencies Laravel (tanpa dev)
      - name: Install PHP dependencies
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # 3️⃣ Install lftp (alat FTP command-line)
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy via FTP (incremental)
        env:
          FTP_HOST: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "🔍 Testing FTP connection..."
          lftp -u $FTP_USER,$FTP_PASSWORD -e "set ftp:ssl-allow yes; set ssl:verify-certificate no; ls; bye" $FTP_HOST

          echo "🚀 Starting deploy..."
          lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST <<EOF
          set ftp:ssl-allow yes
          set ssl:verify-certificate no
          set net:timeout 10
          set net:max-retries 2
          set net:reconnect-interval-base 5
          
          mirror -R --only-newer --parallel=5 --verbose \
            --exclude .git/ \
            --exclude .github/ \
            --exclude node_modules/ \
            ./ /home/aisk7155/public_html/be.aissystem.org/ams/
          bye
          EOF

